# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splash_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1061, 853)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color:rgb(255, 210, 211)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(230, 0, 591, 211))
        self.widget.setStyleSheet("QWidget{\n"
"    background-color:white\n"
"}")
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 101, 31))
        self.label_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.titleEdit = QtWidgets.QLineEdit(self.widget)
        self.titleEdit.setGeometry(QtCore.QRect(110, 10, 281, 31))
        self.titleEdit.setText("")
        self.titleEdit.setObjectName("titleEdit")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(50, 10, 51, 31))
        self.label.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.contentEdit = QtWidgets.QLineEdit(self.widget)
        self.contentEdit.setGeometry(QtCore.QRect(110, 50, 281, 141))
        self.contentEdit.setText("")
        self.contentEdit.setObjectName("contentEdit")
        self.updateButton = QtWidgets.QPushButton(self.widget)
        self.updateButton.setGeometry(QtCore.QRect(430, 80, 131, 41))
        self.updateButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color:yellow\n"
"}")
        self.updateButton.setObjectName("updateButton")
        self.addButton = QtWidgets.QPushButton(self.widget)
        self.addButton.setGeometry(QtCore.QRect(430, 10, 131, 41))
        self.addButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color:green\n"
"}")
        self.addButton.setObjectName("addButton")
        self.deleteButton = QtWidgets.QPushButton(self.widget)
        self.deleteButton.setGeometry(QtCore.QRect(430, 150, 131, 41))
        self.deleteButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color:red\n"
"}")
        self.deleteButton.setObjectName("deleteButton")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(230, 300, 831, 481))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(230, 230, 281, 41))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(-1, -1, 221, 781))
        self.widget_2.setStyleSheet("QWidget{\n"
"background-color:rgb(64, 106, 107)\n"
"}")
        self.widget_2.setObjectName("widget_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1061, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Content:"))
        self.label.setText(_translate("MainWindow", "Title:"))
        self.updateButton.setText(_translate("MainWindow", "Update Todo"))
        self.addButton.setText(_translate("MainWindow", "Add Todo"))
        self.deleteButton.setText(_translate("MainWindow", "Delete Todo"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Open Date"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Days Open"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Content"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Open"))
        self.comboBox.setItemText(1, _translate("MainWindow", "In Progress"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Done"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
